// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "bHIVE_types.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_affinity_matrix
arma::mat compute_affinity_matrix(const arma::mat& X, const arma::mat& A, const std::string& affinity_type, double alpha, double c, double p);
RcppExport SEXP _bHIVE_compute_affinity_matrix(SEXP XSEXP, SEXP ASEXP, SEXP affinity_typeSEXP, SEXP alphaSEXP, SEXP cSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const std::string& >::type affinity_type(affinity_typeSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_affinity_matrix(X, A, affinity_type, alpha, c, p));
    return rcpp_result_gen;
END_RCPP
}
// compute_distance_matrix
arma::mat compute_distance_matrix(const arma::mat& X, const arma::mat& A, const std::string& dist_type, double p, const arma::mat& Sigma_inv);
RcppExport SEXP _bHIVE_compute_distance_matrix(SEXP XSEXP, SEXP ASEXP, SEXP dist_typeSEXP, SEXP pSEXP, SEXP Sigma_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dist_type(dist_typeSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_inv(Sigma_invSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_distance_matrix(X, A, dist_type, p, Sigma_inv));
    return rcpp_result_gen;
END_RCPP
}
// compute_pairwise_distance
arma::mat compute_pairwise_distance(const arma::mat& A, const std::string& dist_type, double p, const arma::mat& Sigma_inv);
RcppExport SEXP _bHIVE_compute_pairwise_distance(SEXP ASEXP, SEXP dist_typeSEXP, SEXP pSEXP, SEXP Sigma_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dist_type(dist_typeSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_inv(Sigma_invSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_pairwise_distance(A, dist_type, p, Sigma_inv));
    return rcpp_result_gen;
END_RCPP
}
// clonal_selection_iteration_cpp
Rcpp::List clonal_selection_iteration_cpp(arma::mat A, const arma::mat& X, const arma::vec& y_num, int task_int, int k, double beta, double maxClones, double mutationDecay, double mutationMin, int iter, const std::string& affinity_type, double alpha, double c_param, double p_param, int nClasses);
RcppExport SEXP _bHIVE_clonal_selection_iteration_cpp(SEXP ASEXP, SEXP XSEXP, SEXP y_numSEXP, SEXP task_intSEXP, SEXP kSEXP, SEXP betaSEXP, SEXP maxClonesSEXP, SEXP mutationDecaySEXP, SEXP mutationMinSEXP, SEXP iterSEXP, SEXP affinity_typeSEXP, SEXP alphaSEXP, SEXP c_paramSEXP, SEXP p_paramSEXP, SEXP nClassesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_num(y_numSEXP);
    Rcpp::traits::input_parameter< int >::type task_int(task_intSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type maxClones(maxClonesSEXP);
    Rcpp::traits::input_parameter< double >::type mutationDecay(mutationDecaySEXP);
    Rcpp::traits::input_parameter< double >::type mutationMin(mutationMinSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type affinity_type(affinity_typeSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type c_param(c_paramSEXP);
    Rcpp::traits::input_parameter< double >::type p_param(p_paramSEXP);
    Rcpp::traits::input_parameter< int >::type nClasses(nClassesSEXP);
    rcpp_result_gen = Rcpp::wrap(clonal_selection_iteration_cpp(A, X, y_num, task_int, k, beta, maxClones, mutationDecay, mutationMin, iter, affinity_type, alpha, c_param, p_param, nClasses));
    return rcpp_result_gen;
END_RCPP
}
// final_assignment_cpp
Rcpp::List final_assignment_cpp(const arma::mat& X, const arma::mat& A, const std::string& affinity_type, const std::string& dist_type, int task_int, double alpha, double c_param, double p_param, const arma::mat& Sigma_inv);
RcppExport SEXP _bHIVE_final_assignment_cpp(SEXP XSEXP, SEXP ASEXP, SEXP affinity_typeSEXP, SEXP dist_typeSEXP, SEXP task_intSEXP, SEXP alphaSEXP, SEXP c_paramSEXP, SEXP p_paramSEXP, SEXP Sigma_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const std::string& >::type affinity_type(affinity_typeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dist_type(dist_typeSEXP);
    Rcpp::traits::input_parameter< int >::type task_int(task_intSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type c_param(c_paramSEXP);
    Rcpp::traits::input_parameter< double >::type p_param(p_paramSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_inv(Sigma_invSEXP);
    rcpp_result_gen = Rcpp::wrap(final_assignment_cpp(X, A, affinity_type, dist_type, task_int, alpha, c_param, p_param, Sigma_inv));
    return rcpp_result_gen;
END_RCPP
}
// init_kmeanspp_cpp
arma::mat init_kmeanspp_cpp(const arma::mat& X, int nCenters);
RcppExport SEXP _bHIVE_init_kmeanspp_cpp(SEXP XSEXP, SEXP nCentersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type nCenters(nCentersSEXP);
    rcpp_result_gen = Rcpp::wrap(init_kmeanspp_cpp(X, nCenters));
    return rcpp_result_gen;
END_RCPP
}
// idiotypic_dynamics_cpp
Rcpp::List idiotypic_dynamics_cpp(const arma::mat& A, const std::string& affinity_type, double aff_alpha, double aff_c, double aff_p, double theta_low, double theta_high, double source_rate, double decay_rate, double dt, int timeSteps, double survival_threshold);
RcppExport SEXP _bHIVE_idiotypic_dynamics_cpp(SEXP ASEXP, SEXP affinity_typeSEXP, SEXP aff_alphaSEXP, SEXP aff_cSEXP, SEXP aff_pSEXP, SEXP theta_lowSEXP, SEXP theta_highSEXP, SEXP source_rateSEXP, SEXP decay_rateSEXP, SEXP dtSEXP, SEXP timeStepsSEXP, SEXP survival_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const std::string& >::type affinity_type(affinity_typeSEXP);
    Rcpp::traits::input_parameter< double >::type aff_alpha(aff_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type aff_c(aff_cSEXP);
    Rcpp::traits::input_parameter< double >::type aff_p(aff_pSEXP);
    Rcpp::traits::input_parameter< double >::type theta_low(theta_lowSEXP);
    Rcpp::traits::input_parameter< double >::type theta_high(theta_highSEXP);
    Rcpp::traits::input_parameter< double >::type source_rate(source_rateSEXP);
    Rcpp::traits::input_parameter< double >::type decay_rate(decay_rateSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type timeSteps(timeStepsSEXP);
    Rcpp::traits::input_parameter< double >::type survival_threshold(survival_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(idiotypic_dynamics_cpp(A, affinity_type, aff_alpha, aff_c, aff_p, theta_low, theta_high, source_rate, decay_rate, dt, timeSteps, survival_threshold));
    return rcpp_result_gen;
END_RCPP
}
// network_suppression_cpp
Rcpp::LogicalVector network_suppression_cpp(const arma::mat& A, const std::string& dist_type, double epsilon, double p, const arma::mat& Sigma_inv);
RcppExport SEXP _bHIVE_network_suppression_cpp(SEXP ASEXP, SEXP dist_typeSEXP, SEXP epsilonSEXP, SEXP pSEXP, SEXP Sigma_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dist_type(dist_typeSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma_inv(Sigma_invSEXP);
    rcpp_result_gen = Rcpp::wrap(network_suppression_cpp(A, dist_type, epsilon, p, Sigma_inv));
    return rcpp_result_gen;
END_RCPP
}
// shm_mutate_cpp
Rcpp::List shm_mutate_cpp(const arma::mat& A, const arma::mat& X, const arma::vec& affinities, const arma::uvec& top_k_indices, const arma::uvec& data_indices, const std::string& method, int iter, double decay, double mutationMin, double c_rate, double temperature, double E_0, double base_rate, double beta1, double beta2, double adam_epsilon, arma::mat m1_state, arma::mat m2_state, const std::string& affinity_type, double aff_alpha, double aff_c, double aff_p);
RcppExport SEXP _bHIVE_shm_mutate_cpp(SEXP ASEXP, SEXP XSEXP, SEXP affinitiesSEXP, SEXP top_k_indicesSEXP, SEXP data_indicesSEXP, SEXP methodSEXP, SEXP iterSEXP, SEXP decaySEXP, SEXP mutationMinSEXP, SEXP c_rateSEXP, SEXP temperatureSEXP, SEXP E_0SEXP, SEXP base_rateSEXP, SEXP beta1SEXP, SEXP beta2SEXP, SEXP adam_epsilonSEXP, SEXP m1_stateSEXP, SEXP m2_stateSEXP, SEXP affinity_typeSEXP, SEXP aff_alphaSEXP, SEXP aff_cSEXP, SEXP aff_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type affinities(affinitiesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type top_k_indices(top_k_indicesSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type data_indices(data_indicesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< double >::type decay(decaySEXP);
    Rcpp::traits::input_parameter< double >::type mutationMin(mutationMinSEXP);
    Rcpp::traits::input_parameter< double >::type c_rate(c_rateSEXP);
    Rcpp::traits::input_parameter< double >::type temperature(temperatureSEXP);
    Rcpp::traits::input_parameter< double >::type E_0(E_0SEXP);
    Rcpp::traits::input_parameter< double >::type base_rate(base_rateSEXP);
    Rcpp::traits::input_parameter< double >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< double >::type beta2(beta2SEXP);
    Rcpp::traits::input_parameter< double >::type adam_epsilon(adam_epsilonSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type m1_state(m1_stateSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type m2_state(m2_stateSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type affinity_type(affinity_typeSEXP);
    Rcpp::traits::input_parameter< double >::type aff_alpha(aff_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type aff_c(aff_cSEXP);
    Rcpp::traits::input_parameter< double >::type aff_p(aff_pSEXP);
    rcpp_result_gen = Rcpp::wrap(shm_mutate_cpp(A, X, affinities, top_k_indices, data_indices, method, iter, decay, mutationMin, c_rate, temperature, E_0, base_rate, beta1, beta2, adam_epsilon, m1_state, m2_state, affinity_type, aff_alpha, aff_c, aff_p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bHIVE_compute_affinity_matrix", (DL_FUNC) &_bHIVE_compute_affinity_matrix, 6},
    {"_bHIVE_compute_distance_matrix", (DL_FUNC) &_bHIVE_compute_distance_matrix, 5},
    {"_bHIVE_compute_pairwise_distance", (DL_FUNC) &_bHIVE_compute_pairwise_distance, 4},
    {"_bHIVE_clonal_selection_iteration_cpp", (DL_FUNC) &_bHIVE_clonal_selection_iteration_cpp, 15},
    {"_bHIVE_final_assignment_cpp", (DL_FUNC) &_bHIVE_final_assignment_cpp, 9},
    {"_bHIVE_init_kmeanspp_cpp", (DL_FUNC) &_bHIVE_init_kmeanspp_cpp, 2},
    {"_bHIVE_idiotypic_dynamics_cpp", (DL_FUNC) &_bHIVE_idiotypic_dynamics_cpp, 12},
    {"_bHIVE_network_suppression_cpp", (DL_FUNC) &_bHIVE_network_suppression_cpp, 5},
    {"_bHIVE_shm_mutate_cpp", (DL_FUNC) &_bHIVE_shm_mutate_cpp, 22},
    {NULL, NULL, 0}
};

RcppExport void R_init_bHIVE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
