# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_affinity_matrix <- function(X, A, affinity_type, alpha = 1.0, c = 1.0, p = 2.0) {
    .Call(`_bHIVE_compute_affinity_matrix`, X, A, affinity_type, alpha, c, p)
}

compute_distance_matrix <- function(X, A, dist_type, p, Sigma_inv) {
    .Call(`_bHIVE_compute_distance_matrix`, X, A, dist_type, p, Sigma_inv)
}

compute_pairwise_distance <- function(A, dist_type, p, Sigma_inv) {
    .Call(`_bHIVE_compute_pairwise_distance`, A, dist_type, p, Sigma_inv)
}

clonal_selection_iteration_cpp <- function(A, X, y_num, task_int, k, beta, maxClones, mutationDecay, mutationMin, iter, affinity_type, alpha, c_param, p_param, nClasses) {
    .Call(`_bHIVE_clonal_selection_iteration_cpp`, A, X, y_num, task_int, k, beta, maxClones, mutationDecay, mutationMin, iter, affinity_type, alpha, c_param, p_param, nClasses)
}

final_assignment_cpp <- function(X, A, affinity_type, dist_type, task_int, alpha, c_param, p_param, Sigma_inv) {
    .Call(`_bHIVE_final_assignment_cpp`, X, A, affinity_type, dist_type, task_int, alpha, c_param, p_param, Sigma_inv)
}

init_kmeanspp_cpp <- function(X, nCenters) {
    .Call(`_bHIVE_init_kmeanspp_cpp`, X, nCenters)
}

idiotypic_dynamics_cpp <- function(A, affinity_type, aff_alpha, aff_c, aff_p, theta_low, theta_high, source_rate, decay_rate, dt, timeSteps, survival_threshold) {
    .Call(`_bHIVE_idiotypic_dynamics_cpp`, A, affinity_type, aff_alpha, aff_c, aff_p, theta_low, theta_high, source_rate, decay_rate, dt, timeSteps, survival_threshold)
}

network_suppression_cpp <- function(A, dist_type, epsilon, p, Sigma_inv) {
    .Call(`_bHIVE_network_suppression_cpp`, A, dist_type, epsilon, p, Sigma_inv)
}

shm_mutate_cpp <- function(A, X, affinities, top_k_indices, data_indices, method, iter, decay, mutationMin, c_rate, temperature, E_0, base_rate, beta1, beta2, adam_epsilon, m1_state, m2_state, affinity_type, aff_alpha, aff_c, aff_p) {
    .Call(`_bHIVE_shm_mutate_cpp`, A, X, affinities, top_k_indices, data_indices, method, iter, decay, mutationMin, c_rate, temperature, E_0, base_rate, beta1, beta2, adam_epsilon, m1_state, m2_state, affinity_type, aff_alpha, aff_c, aff_p)
}

