#' @title VDJLibrary
#' @description V(D)J gene library initialization for antibody populations.
#' Instead of random sampling, antibodies are generated by combinatorial
#' assembly of gene segments, mimicking the V(D)J recombination that generates
#' antibody diversity in real immune systems.
#'
#' @details
#' The feature space is decomposed into V, D, and J segments (subsets of
#' dimensions). Each segment is discretized into "alleles" by clustering.
#' New antibodies are generated by combinatorial sampling of one allele from
#' each segment, producing structured coverage of the data manifold.
#'
#' Methods:
#' \itemize{
#'   \item \code{"pca"}: PCA components define gene segments
#'   \item \code{"cluster"}: k-means within dimension groups creates alleles
#'   \item \code{"random_partition"}: Random feature grouping
#' }
#'
#' @examples
#' # Generate antibodies via V(D)J combinatorial assembly
#' data(iris)
#' X <- as.matrix(iris[, 1:4])
#' vdj <- VDJLibrary$new(nV = 5, nD = 3, nJ = 3, method = "pca")
#' A <- vdj$generate(20, X)
#' dim(A)  # 20 x 4
#' print(vdj)
#'
#' @importFrom R6 R6Class
#' @importFrom stats prcomp kmeans
#' @export
VDJLibrary <- R6::R6Class(
  "VDJLibrary",
  public = list(

    #' @field nV Number of V gene segments.
    nV = NULL,

    #' @field nD Number of D gene segments.
    nD = NULL,

    #' @field nJ Number of J gene segments.
    nJ = NULL,

    #' @field method Decomposition method.
    method = NULL,

    #' @field library The computed gene library (list of allele matrices).
    library = NULL,

    #' @description Create a new VDJLibrary.
    #' @param nV Integer. Number of V gene alleles.
    #' @param nD Integer. Number of D gene alleles.
    #' @param nJ Integer. Number of J gene alleles.
    #' @param method Character. "pca", "cluster", or "random_partition".
    initialize = function(nV = 10, nD = 5, nJ = 4, method = "pca") {
      self$nV     <- nV
      self$nD     <- nD
      self$nJ     <- nJ
      self$method <- match.arg(method, c("pca", "cluster", "random_partition"))
    },

    #' @description Build the gene library from training data.
    #' @param X Numeric matrix (n x d).
    #' @return Invisible self.
    build = function(X) {
      X <- as.matrix(X)
      d <- ncol(X)

      if (self$method == "pca") {
        self$library <- private$.build_pca(X)
      } else if (self$method == "cluster") {
        self$library <- private$.build_cluster(X)
      } else {
        self$library <- private$.build_random(X)
      }
      invisible(self)
    },

    #' @description Generate antibodies by combinatorial V(D)J assembly.
    #' @param nAntibodies Integer. Number of antibodies to generate.
    #' @param X Numeric matrix. Training data (used to build library if needed).
    #' @return Numeric matrix (nAntibodies x d).
    generate = function(nAntibodies, X) {
      if (is.null(self$library)) self$build(X)

      lib <- self$library
      d <- ncol(as.matrix(X))
      A <- matrix(0, nrow = nAntibodies, ncol = d)

      for (i in seq_len(nAntibodies)) {
        v_idx <- sample.int(nrow(lib$V), 1)
        d_idx <- sample.int(nrow(lib$D), 1)
        j_idx <- sample.int(nrow(lib$J), 1)

        # Concatenate gene segments
        A[i, lib$V_dims] <- lib$V[v_idx, ]
        A[i, lib$D_dims] <- lib$D[d_idx, ]
        A[i, lib$J_dims] <- lib$J[j_idx, ]
      }

      A
    },

    #' @description Print summary.
    print = function(...) {
      cat(sprintf("<VDJLibrary> method='%s' V=%d D=%d J=%d\n",
                  self$method, self$nV, self$nD, self$nJ))
      if (!is.null(self$library)) {
        cat(sprintf("  Combinatorial space: %d antibodies\n",
                    nrow(self$library$V) * nrow(self$library$D) * nrow(self$library$J)))
      }
      invisible(self)
    }
  ),

  private = list(

    .split_dims = function(d) {
      # Split dimensions into 3 non-empty groups
      dims <- seq_len(d)
      if (d == 1) {
        return(list(V = 1L, D = 1L, J = 1L))
      } else if (d == 2) {
        return(list(V = 1L, D = 2L, J = c(1L, 2L)))
      }
      # Split into roughly equal thirds
      breaks <- round(seq(0, d, length.out = 4))
      list(
        V = dims[(breaks[1] + 1):breaks[2]],
        D = dims[(breaks[2] + 1):breaks[3]],
        J = dims[(breaks[3] + 1):breaks[4]]
      )
    },

    .build_pca = function(X) {
      d <- ncol(X)
      splits <- private$.split_dims(d)
      V_dims <- splits$V
      D_dims <- splits$D
      J_dims <- splits$J

      # Create alleles by clustering within each dimension group
      V <- private$.make_alleles(X[, V_dims, drop = FALSE], self$nV)
      D <- private$.make_alleles(X[, D_dims, drop = FALSE], self$nD)
      J <- private$.make_alleles(X[, J_dims, drop = FALSE], self$nJ)

      list(V = V, D = D, J = J, V_dims = V_dims, D_dims = D_dims, J_dims = J_dims)
    },

    .build_cluster = function(X) {
      d <- ncol(X)
      splits <- private$.split_dims(d)
      V_dims <- splits$V
      D_dims <- splits$D
      J_dims <- splits$J

      V <- private$.make_alleles(X[, V_dims, drop = FALSE], self$nV)
      D <- private$.make_alleles(X[, D_dims, drop = FALSE], self$nD)
      J <- private$.make_alleles(X[, J_dims, drop = FALSE], self$nJ)

      list(V = V, D = D, J = J, V_dims = V_dims, D_dims = D_dims, J_dims = J_dims)
    },

    .build_random = function(X) {
      d <- ncol(X)
      perm <- sample.int(d)
      splits <- private$.split_dims(d)
      V_dims <- perm[splits$V]
      D_dims <- perm[splits$D]
      J_dims <- perm[splits$J]

      V <- private$.make_alleles(X[, V_dims, drop = FALSE], self$nV)
      D <- private$.make_alleles(X[, D_dims, drop = FALSE], self$nD)
      J <- private$.make_alleles(X[, J_dims, drop = FALSE], self$nJ)

      list(V = V, D = D, J = J, V_dims = V_dims, D_dims = D_dims, J_dims = J_dims)
    },

    .make_alleles = function(X_sub, k) {
      X_sub <- as.matrix(X_sub)
      # Ensure no NA/NaN/Inf
      if (any(!is.finite(X_sub))) {
        X_sub[!is.finite(X_sub)] <- 0
      }
      # Create k alleles by k-means clustering
      k <- min(k, nrow(unique(X_sub)))
      if (k < 1) k <- 1
      if (k == 1) return(matrix(colMeans(X_sub), nrow = 1))
      km <- kmeans(X_sub, centers = k, nstart = 3)
      km$centers
    }
  )
)
